### ISSUE TITLE
Generated project fails to build with crank

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/BenchmarkDotNet#2128]
The benchmark project: [benchmarks.zip](https://github.com/dotnet/BenchmarkDotNet/files/9690581/benchmarks.zip)

When using a simple benchmark that works fine locally, the build fails if run via crank.

<details>
<summary>benchmarks.yml</summary>

```yml
imports:
  - https://github.com/aspnet/benchmarks/blob/main/scenarios/aspnet.profiles.yml?raw=true

jobs:
  dotnet:
    source:
      localFolder: .
      project: BDNTest.csproj
    variables:
      run: short
    arguments: --job {{run}} --memory --logBuildOutput
    framework: net7.0
    options:
      benchmarkDotNet: true
      displayOutput: true
    
scenarios:
  custom:
    application:
      job: dotnet

```

</details>

```sh
crank --config .\benchmarks.yml --scenario custom --profile aspnet-perf-lin
```

```
[application] // start dotnet  restore /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 /p:Deterministic=true /p:Optimize=true in /tmp/benchmarks-agent/benchmarks-server-1/ynx4yppa.yng/src/published/def9e762-baf6-4278-9a4a-a02ddce0215f
[application] // command took 0s and exited with 145
```

The autogenerated project: [e9b32705-2561-4b25-bab0-f1790f6627c3.zip](https://github.com/dotnet/BenchmarkDotNet/files/9690582/e9b32705-2561-4b25-bab0-f1790f6627c3.zip)

Trying to run the above restore command on the autogenerated project locally fails with
```
BenchmarkDotNet.Autogenerated.csproj(23,25): error MSB4066: The attribute "Update" in element <FrameworkReference> is unrecognized.
```
referring to
```csproj
<FrameworkReference Update="Microsoft.AspNetCore.App" RuntimeFrameworkVersion="$(MicrosoftAspNetCoreAppPackageVersion)" />
<FrameworkReference Update="Microsoft.NETCore.App" RuntimeFrameworkVersion="$(MicrosoftNETCoreAppPackageVersion)" />
```

Any ideas about what went wrong here?
For reference, I can run the [`dotnet/performance` microbenchmarks](https://github.com/aspnet/Benchmarks/tree/main/scenarios#micro-benchmarks) with crank, I'm just failing at adapting that to a custom set of benchmarks.

cc: @sebastienros
